# Documentation for general noise maps creation

**Disclaimer:** This is not working yet.

To create our polytope we can use what we are already using. The insphere that is going to change. 

### Importing the necessary libraries

In [3]:
#Construction:
import picos as pic
import numpy as np
import math
from scipy.spatial import ConvexHull

### Creating the noiseless polytope

Here we will give the vertices of our polyhedron and ask for the ConvexHull function to find the COnvex Hull associated to this.

In [100]:
# Creating the smallest test polyhedron: Octahedron
vert = np.array([[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]])
#print(vert)
# Construct the polyhedron
hull = ConvexHull(vert)
facets = hull.equations
print(facets)
#print(facets.shape[0])

[[-0.57735027 -0.57735027 -0.57735027 -0.57735027]
 [ 0.57735027 -0.57735027 -0.57735027 -0.57735027]
 [-0.57735027 -0.57735027  0.57735027 -0.57735027]
 [ 0.57735027 -0.57735027  0.57735027 -0.57735027]
 [ 0.57735027  0.57735027 -0.57735027 -0.57735027]
 [-0.57735027  0.57735027 -0.57735027 -0.57735027]
 [ 0.57735027  0.57735027  0.57735027 -0.57735027]
 [-0.57735027  0.57735027  0.57735027 -0.57735027]]


### Creating the noise map
Given the noise map
$$\Phi^\eta (A_a) = \eta A_a+(1-\eta)\text{Tr}(\xi A_a)\mathbb{1}\equiv A_a^\eta$$
it is necessary to choose the density matrix $\xi$, which defines the map. In [Hirsch2016](https://arxiv.org/abs/1512.00262) they have observed that the best choice of $\xi$ depends on the input state and conjecture that the optimal choice of $\xi$ is setting $\xi = \text{tr}_B(\rho_{\text{sep}})$. When considering a general noise map $\Phi^\eta$, $\xi$ will be an arbitrary qubit state $\xi = (\mathbb{1}+\vec{u}\cdot\vec{\sigma})/2$ .

In [51]:
u = np.array([0,0,0])

# Horodecki = (0,0,1)

xi = np.array([[1+u[2],u[0]-u[1]],[u[0]+u[1],1-u[2]]])/2

print(xi)

[[0.5 0. ]
 [0.  0.5]]


### Finding the shrinking factor

We want 
$$\eta^{*}\left(\left\lbrace A_{a|x}\right\rbrace,\xi_{A}\right) = \underset{j}{\text{min}} ~\eta^{*}_{j}\left(\vec{F}_{j},b_{j},\xi_{A}\right), \qquad j = 1,\ldots,N_{F}.$$

We will obtain a quadratic expression for $\eta(\vec{F},b,\xi_{A})$, namely,
$$A\eta^{2} + B\eta + C = 0,$$
with
$$A = \sum_{k=1}^{3}\left(F_{k} {-} F_{0} u_{k}\right)^{2}$$
$$B = 4F_{0}\sum_{k=1}^{3}u_{k}\left(F_{k} {-} F_{0}u_{k}\right)$$
$$C = 4b\left(F_{0} {-} b\right),$$
$\eta^{*}$ being the largest of the two solutions to this equation and $N_F$ being the number of facets.

In [99]:
# Here we will calculate A, B and C

# We hope to find this radius for de despolarizing map
r = np.min(np.abs(facets[:, -1]))
print(r)

for j in range(facets.shape[0]):

    #print(facets[j,:])

    F_0 = facets[j,0]
    F_1 = facets[j,1]
    F_2 = facets[j,2]
    F_3 = facets[j,3]
    b = facets[j,4]

    #F_0 = 1/2
    #F_1 = facets[j,0]
    #F_2 = facets[j,1]
    #F_3 = facets[j,2]
    #b = facets[j,3]

    A = (F_1-F_0*u[0])**2+(F_2-F_0*u[1])**2+(F_3-F_0*u[2])**2
    B = 4*F_0*(u[0]*(F_1-F_0*u[0])+u[1]*(F_2-F_0*u[1])+u[2]*(F_3-F_0*u[2]))
    C = 4*b*(F_0-b)

    print(A,B,C)

    eta_1 = (-B+np.sqrt(B**2-4*A*C))/2*A
    eta_2 = (-B-np.sqrt(B**2-4*A*C))/2*A

    print(eta_1,eta_2)

0.2886751345948129
1.0000000000000002 -0.0 -0.9106836025229592
0.9542974392310606 -0.9542974392310606
1.0000000000000002 0.0 -0.9106836025229592
0.9542974392310606 -0.9542974392310606
1.0000000000000002 0.0 -0.9106836025229592
0.9542974392310606 -0.9542974392310606
1.0000000000000002 0.0 -0.9106836025229592
0.9542974392310606 -0.9542974392310606
1.0000000000000002 0.0 -0.9106836025229592
0.9542974392310606 -0.9542974392310606
1.0000000000000002 0.0 -0.9106836025229592
0.9542974392310606 -0.9542974392310606
1.0000000000000002 0.0 -0.9106836025229592
0.9542974392310606 -0.9542974392310606
1.0000000000000002 0.0 -0.9106836025229592
0.9542974392310606 -0.9542974392310606
